# Generated by Django 4.2.4 on 2023-09-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=300, unique=True)),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('images', models.ImageField(upload_to='photos/books')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('modified_pub', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_category.category')),
            ],
        ),
    ]
