# Generated by Django 4.2.4 on 2023-09-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_alter_books_first_pub_alter_books_modified_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
