# Generated by Django 4.2.4 on 2023-09-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_alter_books_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
